### ISSUE TITLE
Youtube advertisements aren't showing up

### ISSUE THREAD

**Issue by RohithKilaparthi** [sarbagyastha/youtube_player_flutter#117]
**Describe the bug**
Not able to see the adds which show up in youtube video

**Comment by RohithKilaparthi** [comment]
@sarbagyastha Can you comment on this? I see that embedded videos can have youtube ads but somehow these are not being shown in the app with this plugin.

**Comment by sarbagyastha** [comment]
![Requirements for Ads](https://user-images.githubusercontent.com/9782008/68868753-2b98bf00-0720-11ea-9980-479664c9dadf.jpg)

Source: [Google Support](https://support.google.com/youtube/answer/132596?hl=en)

**Comment by RohithKilaparthi** [comment]
Thanks for the update @sarbagyastha 
So, my question is, it was said that Google closely evaluates the websites and then show the adds to the users. 
1) Would they be shown up in the apps? 
2) Have you already tried anything such?
3) How to show the adds in the embedded video in the app?

**Comment by RohithKilaparthi** [comment]
@sarbagyastha any update here?

**Comment by sarbagyastha** [comment]
There's no clear description about why ads are not showing up in web based player using Youtube Iframe API. It might be due to HTML5 players in webviews or the API itself intends to not show ads. 

Ads are also not showing up in desktop-based browsers too. When inspected with developer tools, some files related to ads are being downloaded, but it's showing as if it is an error.

So, as of now, ads won't show up with the player. Ads delivery is controlled by the iframe API, so there's nothing we can do for it.

**Comment by shahidcodes** [comment]
@sarbagyastha Won't it voilate Google Play Developer policy if ads does not show up?

**Comment by sarbagyastha** [comment]
> @sarbagyastha Won't it violate Google Play Developer policy if ads does not show up?

It shouldn't as we're basically using the tool provided by Youtube itself and is not custom made.

**Comment by nrbn** [comment]
Without ads not showing, it looks like app does not work properly. So it is possible to fix?

**Comment by nrbn** [comment]
Is it possible to get status of if ad is playing now? then i can just show message to user, now ads playing in background and wait for video?

Will it play long ads that not possible to skip? i feel this is very important to get fixed

**Comment by sarbagyastha** [comment]
> Without ads not showing, it looks like app does not work properly. So it is possible to fix?
@nrbn What's not working?

**Comment by sarbagyastha** [comment]
#289
