### ISSUE TITLE
Fullscreen and paused video

### ISSUE THREAD

**Issue by kamathprasad9** [sarbagyastha/youtube_player_flutter#227]
**When the video is paused**
The video name on youtube along with the option of the video, which normally appears in webview of youtube, comes up. Also, this option (list) button does not do anything when tapper. Meaning it is clearly portraying the webview directly.

**When the video is paused in fullscreen**
As stated above, it again streams the webview results. The video name along with watch later and share icons come up. In the bottom section, some video suggestions arise. All these are unresponsive

**Screenshots**
When the video is paused:
![WhatsApp Image 2020-05-18 at 9 43 50 PM](https://user-images.githubusercontent.com/54414375/82236207-6a1e6900-9951-11ea-8b57-542158e41394.jpeg)

When the video is paused in fullscreen mode:
![WhatsApp Image 2020-05-18 at 9 43 50 PM (1)](https://user-images.githubusercontent.com/54414375/82236201-68ed3c00-9951-11ea-8c32-4cc0d292525b.jpeg)

**Comment by shaheemMPM** [comment]
I'm also finding this irritating, is there a way to remove it??

**Comment by kamathprasad9** [comment]
@shaheemMPM  The package uses iframes. So there is no way to avoid those unfortunately

**Comment by shaheemMPM** [comment]
> @shaheemMPM The package uses iframes. So there is no way to avoid those unfortunately

Thanks For replying, I was wondering if we can inject any JavaScript or CSS to hide these since it is an iframe. 
I'll explain what is my real requirement.
I'm using this player to play unlisted youtube videos in my application for which the video URL is provided through the Admin application. I don't want my users to get the URL of the video so they can download this. and showing the share button and watch later options are kind of inappropriate.
although the share option is not working in the plugin as of now, I'm worried that if this share option starts working my users will be able to get the URL of the video and I don't want that to happen.

I hope you can understand the scenario. Please give some suggestions on this and comment on what you think of it.

**Comment by sarbagyastha** [comment]
@shaheemMPM There's a way to hide it by injecting js snippet, as in this PR #216 . But it might be against YouTube TOS.

**Comment by shaheemMPM** [comment]
> @shaheemMPM There's a way to hide it by injecting js snippet, as in this PR #216 . But it might be against YouTube TOS.

Ok, I'll give a shot. Thanks for the input. and most of all thanks for the plugin 👍
