### ISSUE TITLE
Any Support this plugin Provide regarding thumbnail of a Video.?

### ISSUE THREAD

**Issue by marslannasr7koncepts** [sarbagyastha/youtube_player_flutter#569]
Hi.

I want to show thumbnail of a video instead of YouTube Player running kindly tell me I can fetch thumbnail image by providing YouTube Video Link or embedd YouTube video link.?

Using these link can I get thumbnail of a YouTube Video.?

Thanks

**Comment by gtu-myowin** [comment]
I really like to know this too. Now the videos load on app start up and slowing down the app performance even though I am using the pageview builder which lazy load off-screen items. 

Loading video instead of just the thumbnail also lags other animation of the app even though video section is off screen. I have tested my app by commenting out the video section and the animation works as expected without lagging.

Kindly help me.

**Comment by sarbagyastha** [comment]
You can use the `YoutubePlayerController.getThumbnail` method to get the thumbnail url for given video id.
