### ISSUE TITLE
Support for flutter web?

### ISSUE THREAD

**Issue by MilesAdamson** [sarbagyastha/youtube_player_flutter#58]
Hi. Your package looks great but I can't get it to work on flutter web. Do you think this is currently possible, or planned for the future?

**Comment by Skquark** [comment]
Same question/request here.. Trying hard to keep my app web compatible because it looks so great in a browser, right?  Hasn't been easy.  The YouTube player is one of the primary capabilities I needed too..  I know there's a lot of io dependancies out of our control that currently breaks, but wondering if there's a chance to workaround to eventually get this working on web?

**Comment by sarbagyastha** [comment]
I'll look into it.

**Comment by dheerajsarwaiya** [comment]
looking forward for web support

**Comment by itsMatoosh** [comment]
Any news on this?

**Comment by d-apps** [comment]
Any news?

**Comment by sarbagyastha** [comment]
At the time this PR was raised. Iframes would rebuilt infinitly in web. Haven't tried in web for a while, will test if the issue still persists soon.

**Comment by BrutalCoding** [comment]
> At the time this PR was raised. Iframes would rebuilt infinitly in web. Haven't tried in web for a while, will test if the issue still persists soon.

Hi, 

I've had that before too, not sure since when it - changed but my iFrames do not rebuild infinitly anymore (e.g. when scrolling). Running on Flutter beta channel (1.18-0-11.1.pre) today.

However I hope you can find a solution so that the iFrames are not capturing all input from the user anymore. As of now, if I got YouTube video's (iFrames) next to each other exceeding the screen, you would usually scroll (horizontally) but since the iFrames are stealing the input, Flutter doesn't know that. Which means scrolling doesn't work.

**Comment by sarbagyastha** [comment]
@BrutalCoding Thanks for the info. Will look into it.

**Comment by sarbagyastha** [comment]
[Related Issue](https://github.com/flutter/flutter/issues/56477)

**Comment by BrutalCoding** [comment]
> **Related Issue** [flutter/#56477](https://github.com/flutter/flutter/issues/56477) [flutter/#55430](https://github.com/flutter/flutter/issues/55430)

These issues are not happening on my end, you can check out some YouTube video's here [purrgames.brutalcoding.com](PurrGames) (flutter web).

Most of the games contain YouTube videos on the bottom of their page. Now I'm not sure anymore if I did have the issue and fixed it, or that it's simply not an issue anymore with Flutter for web. 

Let me know if you want to know more, or work together to get your plugin compatible with Web.

**Comment by sarbagyastha** [comment]
Added web support through https://pub.dev/packages/youtube_player_iframe .
 Will soon migrate the current plugin too.

**Comment by paketeserrano** [comment]
Thanks for the work on this flutter plugin. I am using youtube_player_flutter and I realized that it's not working on web. I saw that you fixed it for the youtube_player_iframe, do you have plans to move it to youtube_player_flutter? Not sure if there is a separate ticket for that.
